### ISSUE TITLE
Match Summary Improvements

### ISSUE THREAD

**Issue by thordy** [Chmieloo/ttapp#29]
Some suggestion for improvements to the new Match Summary page

- Add information about Tournament / Group 
- Add general information on top of the view
    - Overview of each set, points scored etc
    - Length of match
- When hovering over a point, show the time it took for this point.
    - This will give an indication of how long each really was 
    - Example is: Point 1 `00:10`, Point 2 `00:21`, Point 3 `00:02` etc
- Make the set information below timeline more readable

**Comment by Chmieloo** [comment]
Done.
